services:
  postgres:
    image: postgres
    volumes:
      - bet-api-volume:/var/lib/postgresql/data
    container_name: postgres-container
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - bet-api-network
  bet-api:
    build: ./
    container_name: bet-api-container
    ports:
      - "5500:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/Bet?schema=public
    networks:
      - bet-api-network
    depends_on:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=hadok@dev.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    networks:
      - bet-api-network
networks:
  bet-api-network:
volumes:
  bet-api-volume: